### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [sentient-lang/sentient-lang#1]
Hello @tuzz ,
I am the member of cdnjs project.
We want to host this library.
But there is a question want to ask.
Which files need to be hosted.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8730

**Comment by tuzz** [comment]
That's great news, thanks!

It's just [`bin/sentient.js`](https://github.com/sentient-lang/sentient-lang/blob/gh-pages/bin/sentient.js). This includes the entire compiler and runtime for the language.

**Comment by kennynaoh** [comment]
So there are not necessary to add any dependent js file, for example in [here](https://github.com/sentient-lang/sentient-lang/tree/gh-pages/lib/sentient), right?
Thanks!

**Comment by tuzz** [comment]
Not necessary.

All of those dependencies are minified to bin/sentient.js.

Thanks

**Comment by kennynaoh** [comment]
But `bin/sentient.js` doesn't exist on [npm](https://www.npmjs.com/package/sentient-lang).
What should I need to add on npm?
Thanks!

**Comment by tuzz** [comment]
Ahh, I just saw this:

> All new libraries hosted on CDNJS should have an official public repository or npm package, and the officially pre-built distribution file(s) should also be there, so that we can apply the auto-update mechanism on that lib.

Currently, `bin/sentient.js` isn't included in the npm package. I'll add this and publish a new version in the next 2 hours.

Thanks!

**Comment by tuzz** [comment]
@kennynaoh: I have now added `bin/` to the package.

https://www.npmjs.com/package/sentient-lang

https://github.com/sentient-lang/sentient-lang/commit/f6b7d49c89d94af6fbb59a466ef91ed02a5f1417

**Comment by kennynaoh** [comment]
How about version `0.0.0-alpha.27`~`0.0.0-alpha.39`?
Thanks!

**Comment by tuzz** [comment]
Is it possible to start from `0.0.0-alpha.40` ? I don't mind if `27~39` aren't hosted.

Or does that cause a problem?

**Comment by tuzz** [comment]
Hi @kennynaoh, do I need to do anything for this? Thanks.

**Comment by kennynaoh** [comment]
Hello @tuzz ,
Sorry for late response.
I think it's ok.
I will add this library as soon as possible.
If there are any problem, I will ask.
Thanks very much!

**Comment by tuzz** [comment]
Hi @kennynaoh, can I help in any way? It's no trouble.

**Comment by tuzz** [comment]
Brilliant! Thanks for your help @kennynaoh!

**Comment by kennynaoh** [comment]
You are welcome!
