### ISSUE TITLE
When target variable is not provided it chooses some value

### ISSUE THREAD

**Issue by malisetti** [sentient-lang/sentient-lang#5]
> cat hello.snt

```
int a, b, c, target;

invariant a + b + c == target;
invariant a > 0, b > 0, c > 0;
invariant a != b, b != c, c != a;

expose a, b, c, target;
```
> sentient -c hello.snt > ten.json

> sentient -r ten.json
{"a":2,"b":10,"c":5,"target":17}

how is the target chosen as 17 ?

**Comment by tuzz** [comment]
Sentient tries to find a way to satisfy the program according to the invariants. There are no invariants for `target` so it is free to choose any number that is in the range of the `int` type which is from -128 to 127. I hope that helps.
