### ISSUE TITLE
Invalid asm.js: Undeclared assignment target

### ISSUE THREAD

**Issue by malisetti** [sentient-lang/sentient-lang#6]
sentient command gives this warning when running a program with -r.

sentient -r ten.json 
{"a":2,"b":10,"c":5,"target":17}
(node:14337) V8: /home/seshachalamm/.npm-global/lib/node_modules/sentient-lang/vendor/minisat.js:4 Invalid asm.js: Undeclared assignment target

**Comment by brweber2** [comment]
Seeing the same issue.

Sentient: 0.0.0-alpha.42
Node: v12.9.1
macOS: 10.14.6

**Comment by tuzz** [comment]
I'm seeing this too. Will investigate.

**Comment by tuzz** [comment]
This should now be fixed. I've released a new version.

If you're on Mac: `brew upgrade sentient-lang`

Let me know if you have any problems. Thanks!
